Adds example from PerfDetective to the test suite
se-sic/FeaturePerfCSCollection pull request #4
Opened 2022-06-09 09:03 UTC by vulder

2022-06-22 12:51 UTC, vulder commented
@Kaufi-Jonas Can you please take a look at this PR?
 Somehow, I cannot add you as a reviewer :roll_eyes:

2022-06-22 12:54 UTC, vulder commented on src/PerfDetectiveExample/CMakeLists.txt
> +)
```suggestion
```

2022-06-30 12:27 UTC, Kaufi-Jonas requested changes
What is the general idea behind this? Do you plan to stress the analysis/instrumentation to check if there are still issues, especially regarding for-loops, which were a problem in the past?

2022-06-30 12:27 UTC, Kaufi-Jonas commented on src/PerfDetectiveExample/PDEmain.cpp
> +}
Might be optimized out, which can be prevented by declaring x2 volatile. Do you plan to also check here how instrumentation behaves under optimization?

2022-06-30 14:34 UTC, vulder commented on src/PerfDetectiveExample/PDEmain.cpp
> +}
No, that's not relevant here. This file just encodes an example from a related paper.
I want to make sure that can handle cases like the ones they explained.

2022-06-30 14:47 UTC, jonas-kaufmann approved these changes

2022-06-30 18:32 UTC, merged